pipeline:
        #  build:
        #    image: golang:1.9
        #    commands:
        #    - 
        #    - go build -a -ldflags '-s' -installsuffix cgo -o app .
  docker:
    image: plugins/docker
    repo: quay.io/nicholas_lane/cleathitch:drone
    dockerfile: Dockerfile
