clusters:
  - name: cleathitch
    cluster:
      server: https://<WORKER NODE IP ADDRESS>:32002
      certificate-authority: /etc/kubernetes/pki/ca.crt

# users refers to the API server's webhook configuration.
users:
  - name: cleathitch
    user:
      client-certificate: /etc/kubernetes/webhook/tls.crt # cert for the webhook plugin to use
      client-key: /etc/kubernetes/webhook/tls.key          # key matching the cert

# kubeconfig files require a context. Provide one for the API server.
current-context: webhook
contexts:
- context:
    cluster: cleathitch 
    user: cleathitch
  name: webhook

