# clusters refers to the remote service. 15 Create a secret containing a TLS certificate and it's key.
 16 
 17 `kubectl create secret generic cleathitchsecret --from-file=./t    ls.cert --from-file=./tls.key`

clusters:
  - name: cleathitch
    cluster:
      server: https://192.168.107.102:32002
      certificate-authority: /etc/kubernetes/pki/ca.crt

# users refers to the API server's webhook configuration.
users:
  - name: cleathitch
    user:
      client-certificate: /etc/kubernetes/webhook/tls.crt # cert for the webhook plugin to use
      client-key: /etc/kubernetes/webhook/tls.key          # key matching the cert

# kubeconfig files require a context. Provide one for the API server.
current-context: webhook
contexts:
- context:
    cluster: cleathitch 
    user: cleathitch
  name: webhook

